on:
  push:
  schedule:
  - cron: "0 0 * * 5"
jobs:
  create_release:
    name: Create Release ISO
    runs-on: self-hosted
    timeout-minutes: 10080
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: 'false'
          submodules: 'true'

      - name: Build ISO
        run: |
          sudo bash -x ./build.sh
      - name: Create md5sum
        run: |
          for f in *.iso; do [ -e "$f" ] && md5sum "$f" > "${f}.md5"; done

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ISO
          if-no-files-found: error
          path: |
            *.iso
            *.md5

      - name: Clean Build Directory
        if: always()
        run: |
          sudo umount -l $(grep ${GITHUB_WORKSPACE} /proc/mounts | cut -f2 -d" " | sort -r) || true
          sudo rm -rf squashfs iso *.iso *.md5 latest-stage3*.txt stat 
